# Generated by Django 5.2.6 on 2025-10-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_internshipconfirmation_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='nilai_konversi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='internshipconfirmation',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
