# Generated by Django 5.2.6 on 2025-10-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_certificate_pdf_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/final_reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.internshipconfirmation')),
            ],
        ),
    ]
