# Generated by Django 5.2.6 on 2025-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipconfirmation',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
