# Generated by Django 5.2.6 on 2025-10-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_certificate_nilai_konversi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
