# Generated by Django 5.2.6 on 2025-10-02 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('bidang_usaha', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('program_studi', models.CharField(max_length=100)),
                ('angkatan', models.CharField(max_length=10)),
                ('jenis_kelamin', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('wa', models.CharField(blank=True, max_length=20)),
                ('bukti_konsultasi', models.FileField(blank=True, null=True, upload_to='documents/konsultasi/')),
                ('bukti_sptjm', models.FileField(blank=True, null=True, upload_to='documents/sptjm/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='documents/cv/')),
                ('portofolio', models.FileField(blank=True, null=True, upload_to='documents/portfolio/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.jobposting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profilestudent')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('posisi', models.CharField(max_length=255)),
                ('alamat_perusahaan', models.TextField(blank=True)),
                ('nama_supervisor', models.CharField(max_length=255)),
                ('email_supervisor', models.EmailField(max_length=254)),
                ('wa_supervisor', models.CharField(blank=True, max_length=50)),
                ('surat_penerimaan', models.FileField(upload_to='documents/surat_penerimaan/')),
                ('date_confirmed', models.DateTimeField(auto_now_add=True)),
                ('is_reported', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profilestudent')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profilestudent')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('filled', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('date_filled', models.DateTimeField(blank=True, null=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.internshipconfirmation')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('profil_perusahaan', models.TextField()),
                ('jobdesk', models.TextField()),
                ('suasana', models.TextField()),
                ('manfaat_dari_perkuliahan', models.TextField()),
                ('kekurangan_pembelajaran', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.internshipconfirmation')),
            ],
            options={
                'unique_together': {('confirmation', 'month')},
            },
        ),
    ]
