# Generated by Django 5.2.6 on 2025-10-03 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf',
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profilestudent')),
            ],
        ),
    ]
